version: "3"

services:
  content-api:
    restart: "unless-stopped"
    container_name: "content-api"
    build:
      context: "content-api/"
      dockerfile: "docker/Dockerfile"
    environment:
      ATLAS_ACCESS: '${ATLAS_ADMIN}'
    volumes:
      - ./content-api/src:/app/api/src
    ports:
      - "8000:8000"
    networks:
      - computing_api_default

  content-registry:
    restart: "unless-stopped"
    container_name: "content-registry"
    build:
      context: "content-regist/"
      dockerfile: "docker/Dockerfile"
    environment:
      ATLAS_ACCESS: '${ATLAS_ADMIN}'
    volumes:
      - ./content-regist/data:/app/content-regist/data    
      - ./content-regist/src:/app/content-regist/src
    ports:
      - "8051:8051"
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true


