version: "3.9"

services:
  content-api:
    restart: "unless-stopped"
    container_name: "content-api"
    build:
      context: "content-api/"
      dockerfile: "docker/Dockerfile"
    expose:
      - "8000"
    ports:
      - "8000:8000"
      
  content-registry:
    restart: "unless-stopped"
    container_name: "content-registry"
    build:
      context: "content-regist/"
      dockerfile: "docker/Dockerfile"
    command: "python3 src/content_registry.py"
    environment:
      DATA_DIR: "${COMPOSE_PROJECT_NAME}_contents"
    volumes:
      - ./content-regist/data:/app/content-regist/data    
      - ./content-regist/src:/app/content-regist/src
    ports:
      - "8051:8051"

volumes: 
  data-m:
    driver: local
    driver_opts:
      type: "none"
      device: "${PWD}/dash-regist/data/"
      o: "bind"