version: "3.9"

services:
  model-api:
    restart: "unless-stopped"
    container_name: "model-api"
    build:
      context: "model-api/"
      dockerfile: "docker/Dockerfile"
    expose:
      - "8000"
    ports:
      - "8000:8000"
      
  model-registry:
    restart: "unless-stopped"
    container_name: "model-registry"
    build:
      context: "model-regist/"
      dockerfile: "docker/Dockerfile"
    command: "python3 src/model_registry.py"
    environment:
      DATA_DIR: "${COMPOSE_PROJECT_NAME}_models"
    volumes:
      - ./model-regist/data:/app/model-regist/data    
      - ./model-regist/src:/app/model-regist/src
    ports:
      - "8051:8051"

volumes: 
  data-m:
    driver: local
    driver_opts:
      type: "none"
      device: "${PWD}/dash-regist/data/"
      o: "bind"