version: "3"

services:
  content-api:
    image: mlexchange1/content-api:1.0
    restart: "unless-stopped"
    container_name: "content-api"
    ports:
      - "8000:8000"
    networks:
      - computing_api_default

  content-registry:
    image: mlexchange1/content-registry:1.0
    restart: "unless-stopped"
    container_name: "content-registry"
    ports:
      - "8051:8051"
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true


