version: "3"

services:
  content-api:
    restart: "unless-stopped"
    container_name: "content-api"
    build:
      context: "content-api/"
      dockerfile: "docker/Dockerfile"
    volumes:
      - ./content-api/src:/app/api/src
    ports:
      - "8000:8000"
    networks:
      - content_registry_network

  content-registry:
    restart: "unless-stopped"
    container_name: "content-registry"
    build:
      context: "content-regist/"
      dockerfile: "docker/Dockerfile"
    volumes:
      - ./content-regist/data:/app/content-regist/data    
      - ./content-regist/src:/app/content-regist/src
    ports:
      - "8051:8051"
    networks:
      - content_registry_network
      - computing_api_default

networks:
  content_registry_network:
    driver: bridge
  computing_api_default:
    external: true


